function [fitresult, gof] = createFit(axial, disp,startPoint,flagFig)
%CREATEFIT(XX,YY)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xx
%      Y Output: yy
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 26-May-2023 18:27:33


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( axial, disp );

% Set up fittype and options.
ft = fittype( 'gauss2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0];
opts.Normalize = 'on';
% opts.StartPoint = [25.5631610036059 -0.920553007911865 0.2429140362903 17.3600207959604 -0.532951741422656 0.340700965754137];
opts.StartPoint = startPoint;
% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
if flagFig
% Plot fit with data.
figure( 'Name', 'Fit : Disp vs Frequency' ); hold all
plot( xData, yData,'ko','markerSize',8,'markerFaceColor','k')
plot( xData, feval(fitresult,xData),'r','LineWidth',2)
leg=legend('data point', 'Fit');
set(leg,'location','best')
% Label axes
xlabel( 'Axial (mm)', 'Interpreter', 'none' );
ylabel( 'Norm Displacement', 'Interpreter', 'none' );
grid on
set(gca,'fontsize',16)
set(gca,'LineWidth',2)
box on
end


